### ISSUE TITLE
[NOT AN ISSUE] Simple request

### ISSUE THREAD

**Issue by EstherMoellman** [tomas-hartman/clean-the-mess#25]
Hi @tomas-hartman ,

Thank you for CleanTheMess.

Please, I have a simple request:
Most of the tab-manager add-ons are using "hiding/discarding" tabs functions.
For privacy/security/performance... I prefer "bookmarking/closing" tabs functions.

At AMO' page you wrote: "My plan is to implement the bookmarks API in a future".  So, perhaps you might be interested on my request. If it is the case, then I offer you my help. I have no JS' knowledge, but I can test your work, I can find bugs etc.

In brief, this is what I'm looking for:
- Tab group manager add-on
- Use bookmarking tab function, instead of hiding
- Use closing tab function, instead of discarding

For example, basically I would like to see something similar to [this addon](https://addons.mozilla.org/en-US/firefox/addon/power-tabs), but instead of "hiding/discarding" tabs, I would like "bookmarking/closing" tabs.
I've seen several session-tab-manager add-ons, that partially do what I'm looking for. But honestly, IMO they are bad. So, I believe a new add-on here may have a niche of opportunity, for those users (like me) looking for tab-group-managers based on "bookmarking/closing" tabs = security/privacy/performance.

Hope you'll be interested!

Thank you in advance!

**Comment by tomas-hartman** [comment]
Hi @EstherMoellman,

Thank you for trying Clean the mess and for your request! My basic point is to keep things as simple and as effective as possible - and to make my browser work as slightly as possible. That's exactly why I don't implement things such as hiding or discarding, but the very simple close (`remove()`) function. Also the "bookmark" feature is planned as soon as in the next, 1.1 version (#14), because I think it is a good idea to have the close forever/save-and-close options next to each other.

I have a similar experience with tab managment addons as you do, I was rarely able to find one that would fit my purpose, even though there is a lot of them (often) packed with a lot of features. I often find these ugly and/or too complicated to use. [Power Tabs](https://addons.mozilla.org/en-US/firefox/addon/power-tabs/) seems nice, but it seems to me that it's focused more on tab managment than cleaning, which is the case of Clean the mess, so if you're looking for more enhanced management or grouping options, they're not planned for Clean the mess at the moment (I'm thinking about some possible sub grouping though #7).

Thanks again for trying my addon and I'll be happy if you report any bugs that you spot! :)

**Comment by EstherMoellman** [comment]
@tomas-hartman , yeah, you're right, I confess I'm a bit more focused on tab management than just tab closing. But after reading your answer, I have the feeling we (you & I) are very close on what we want.

For example, you mentioned that "bookmark" is planned for 1.1 version. So, in principle, this will satisfy the first part of my request. I just hope your future "save-and-close" option, also will be automatic (allowing every tab to be automatically bookmarked when closed).

And you also mentioned "I'm thinking about some possible sub grouping though #7". Today CleanTheMess groups by same url. My request is to group by name group. Simple! Very similar to what you want.

And no, I'm not asking you nothing complicate, sophisticated, fancy etc. I totally identify myself with the first part of your answer: "My basic point is to keep things as simple and as effective as possible - and to make my browser work as slightly as possible".

I shared with you the [PowerTabs](https://addons.mozilla.org/en-US/firefox/addon/power-tabs)' case, precisely just as an example of a simple nice add-on, doing what is expecting from it. I'm looking for a new [PowerTabs](https://addons.mozilla.org/en-US/firefox/addon/power-tabs), but "bookmarking/closing" tabs instead of "hiding/discarding".

Few month ago, a great guy started to develop the add-on I want. Sadly, almost at the end, he abandoned the process forced to attend his personal stuff. If by chance you're still interested in my request, [here is the latest version this great developer built](https://github.com/jingyu9575/tabs-to-bookmark-groups/releases/tag/v0.0.20190911). In my opinion, this add-on is 80% ready, just need small corrections here and there. It's a very simple add-on, grouping tabs, automatically bookmarking everything before closing, and that's all... exactly what I want.

I still hope you'll be interested in this project (hope never dies LOL).
But if you're not interested, please don't worry, I understand, it'll be perfectly fine.

Thank you for your answer and your time! : )

**Comment by tomas-hartman** [comment]
Hi, I think we're not that far away from each other, too and I'll see what I can do. For now just in short:

> I just hope your future "save-and-close" option, also will be automatic (allowing every tab to be automatically bookmarked when closed).

*I have some good news about that, there'll be two buttons: close tab + bookmark-and-close (need to see what FF's bookmark API offers and allows at first though). I added specification to #14*

> My request is to group by name group.

*I added this as an issue to backlog. Although it's not the priority for now, I'll keep it on mind. See #26*

Have a nice day! 
Tom
